# docker-compose.yml
version: '3.8'

services:
  app:
    image: heidarym78/ai-agent:latest 
    container_name: ai-agent
    restart: always
    ports:
      - "8040:8040"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
