# infrastructure\prod-services.yml
version: "3.9"

volumes:
  minio_data:
    driver: local

services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${STORAGE_MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${STORAGE_MINIO_PASSWORD}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - minio_data:/data   # persistent storage
      - ./certs:/root/.minio/certs:ro  # optional TLS certificates
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 5G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5